import type { Metadata } from "next";
import "./globals.css";
import { Suspense } from "react";
import HeaderSwitcher from "@/components/layout/header";
import { Toaster } from "@/components/ui/sonner";
import { getActiveUserId, getAllUsers } from "@/lib/active-user";
import { CounterStoreProvider } from "@/providers/counter-store-provider";
import { UserProvider } from "@/providers/user-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [initialUsers, initialActiveUserId] = await Promise.all([
    getAllUsers(),
    getActiveUserId(),
  ]);

  return (
    <html lang="en">
      <body className="antialiased min-h-screen">
        <UserProvider
          initialUsers={initialUsers}
          initialActiveUserId={initialActiveUserId}
        >
          <Suspense
            fallback={
              <div className="h-16 w-full bg-white border-b border-gray-400" />
            }
          >
            <HeaderSwitcher />
          </Suspense>
          <CounterStoreProvider>{children}</CounterStoreProvider>
        </UserProvider>
        <Toaster />
      </body>
    </html>
  );
}
